= Modular Tiles

A sample modular JavaFX application configured with link:https://github.com/moditect/layrry/[Layrry].

== Build

.Prerequisites

- JDK 11
- Maven 3.6.3 or Gradle 6+ (project includes wrappers for each)
- Layrry 1.0-SNAPSHOT

**NOTE**: Layrry has yet to be published to Maven Central. You have to build your own snapshot for the time being.
JDK 14 is needed to build Layrry.

```sh
$ git clone https://github.com/moditect/layrry.git
$ cd layrry
$ mvn install
```

Once Layrry is installed, change back to where you cloned this repository.

.Maven

```sh
$ ./mvnw install
```

.Gradle

```sh
$ ./gradlew assemble publishToMavenLocal
```

Plugins will be placed under `plugins-prepared` at the root.

== Run

.Maven

```sh
$ ./mvnw -am -pl :modular-tiles-launcher exec:java
```

Or run it directly from the JAR

```sh
$ java -jar app/modular-tiles-launcher/target/modular-tiles-launcher-0.0.0-all.jar
```

.Gradle

```sh
$ ./gradlew :modular-tiles-launcher:run
```

Or run it directly from the JAR

```sh
$ java -jar app/modular-tiles-launcher/build/libs/modular-tiles-launcher-0.0.0-all.jar
```

The `plugins` directory is located at the root. Copy plugins from `plugins-prepared`.

```sh
$ cp -r plugins-prepared/tile-* plugins
```

.jbang

Please note that the supplied layers config files are setup to run on OSX.
Edit these files if you intend to run on Windows or Linux, by replacing all references
of "mac" for "windows" or "linux" as appropriate.

```sh
$ jbang layrry@moditect --layers-config layers.yml
$ jbang layrry@moditect --layers-config layers.toml
```

Remove and add plugins from `plugins` at any time to see dynamic behavior.
